// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: blockchain_interface.proto

package bcinterface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{0}
}

type NodeData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Pubkey    []byte `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *NodeData) Reset() {
	*x = NodeData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeData) ProtoMessage() {}

func (x *NodeData) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeData.ProtoReflect.Descriptor instead.
func (*NodeData) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{1}
}

func (x *NodeData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeData) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *NodeData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EnrollAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *EnrollAccountResponse) Reset() {
	*x = EnrollAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnrollAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollAccountResponse) ProtoMessage() {}

func (x *EnrollAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollAccountResponse.ProtoReflect.Descriptor instead.
func (*EnrollAccountResponse) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollAccountResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type VrfValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val    string `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
	Proof  []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	Pubkey []byte `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (x *VrfValue) Reset() {
	*x = VrfValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfValue) ProtoMessage() {}

func (x *VrfValue) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VrfValue.ProtoReflect.Descriptor instead.
func (*VrfValue) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{3}
}

func (x *VrfValue) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *VrfValue) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *VrfValue) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SetupCommitteeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round     int32     `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Nodeip    string    `protobuf:"bytes,2,opt,name=nodeip,proto3" json:"nodeip,omitempty"`
	Vrfpubkey []byte    `protobuf:"bytes,3,opt,name=vrfpubkey,proto3" json:"vrfpubkey,omitempty"`
	VrfResult *VrfValue `protobuf:"bytes,4,opt,name=vrfResult,proto3" json:"vrfResult,omitempty"`
}

func (x *SetupCommitteeRequest) Reset() {
	*x = SetupCommitteeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupCommitteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCommitteeRequest) ProtoMessage() {}

func (x *SetupCommitteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCommitteeRequest.ProtoReflect.Descriptor instead.
func (*SetupCommitteeRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{4}
}

func (x *SetupCommitteeRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SetupCommitteeRequest) GetNodeip() string {
	if x != nil {
		return x.Nodeip
	}
	return ""
}

func (x *SetupCommitteeRequest) GetVrfpubkey() []byte {
	if x != nil {
		return x.Vrfpubkey
	}
	return nil
}

func (x *SetupCommitteeRequest) GetVrfResult() *VrfValue {
	if x != nil {
		return x.VrfResult
	}
	return nil
}

type SetupCommitteeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SetupCommitteeResponse) Reset() {
	*x = SetupCommitteeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetupCommitteeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCommitteeResponse) ProtoMessage() {}

func (x *SetupCommitteeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCommitteeResponse.ProtoReflect.Descriptor instead.
func (*SetupCommitteeResponse) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{5}
}

func (x *SetupCommitteeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type LeaveRequestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *LeaveRequestResponse) Reset() {
	*x = LeaveRequestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequestResponse) ProtoMessage() {}

func (x *LeaveRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequestResponse.ProtoReflect.Descriptor instead.
func (*LeaveRequestResponse) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRequestResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RequestLeaderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodeinfo string `protobuf:"bytes,1,opt,name=nodeinfo,proto3" json:"nodeinfo,omitempty"`
}

func (x *RequestLeaderRequest) Reset() {
	*x = RequestLeaderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestLeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaderRequest) ProtoMessage() {}

func (x *RequestLeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaderRequest.ProtoReflect.Descriptor instead.
func (*RequestLeaderRequest) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{7}
}

func (x *RequestLeaderRequest) GetNodeinfo() string {
	if x != nil {
		return x.Nodeinfo
	}
	return ""
}

type RequestLeaderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Primarynode string `protobuf:"bytes,1,opt,name=primarynode,proto3" json:"primarynode,omitempty"`
	Code        int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *RequestLeaderResponse) Reset() {
	*x = RequestLeaderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestLeaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestLeaderResponse) ProtoMessage() {}

func (x *RequestLeaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestLeaderResponse.ProtoReflect.Descriptor instead.
func (*RequestLeaderResponse) Descriptor() ([]byte, []int) {
	return file_blockchain_interface_proto_rawDescGZIP(), []int{8}
}

func (x *RequestLeaderResponse) GetPrimarynode() string {
	if x != nil {
		return x.Primarynode
	}
	return ""
}

func (x *RequestLeaderResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_blockchain_interface_proto protoreflect.FileDescriptor

var file_blockchain_interface_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x5a, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x2b, 0x0a, 0x15, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4a, 0x0a, 0x08,
	0x76, 0x72, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x53, 0x65, 0x74,
	0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x70,
	0x12, 0x1c, 0x0a, 0x09, 0x76, 0x72, 0x66, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x72, 0x66, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x34,
	0x0a, 0x09, 0x76, 0x72, 0x66, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x2e, 0x76, 0x72, 0x66, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x76, 0x72, 0x66, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x32,
	0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x69, 0x6e,
	0x66, 0x6f, 0x22, 0x4d, 0x0a, 0x15, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x32, 0xfe, 0x01, 0x0a, 0x13, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0e, 0x45, 0x6e, 0x72,
	0x6f, 0x6c, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x1a, 0x23, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x2e, 0x45, 0x6e, 0x72, 0x6f, 0x6c, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f,
	0x64, 0x75, 0x6c, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0x6c, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x5f,
	0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x75, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x62, 0x63, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_interface_proto_rawDescOnce sync.Once
	file_blockchain_interface_proto_rawDescData = file_blockchain_interface_proto_rawDesc
)

func file_blockchain_interface_proto_rawDescGZIP() []byte {
	file_blockchain_interface_proto_rawDescOnce.Do(func() {
		file_blockchain_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_interface_proto_rawDescData)
	})
	return file_blockchain_interface_proto_rawDescData
}

var file_blockchain_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_blockchain_interface_proto_goTypes = []interface{}{
	(*Empty)(nil),                  // 0: commu_module.Empty
	(*NodeData)(nil),               // 1: commu_module.NodeData
	(*EnrollAccountResponse)(nil),  // 2: commu_module.EnrollAccountResponse
	(*VrfValue)(nil),               // 3: commu_module.vrfValue
	(*SetupCommitteeRequest)(nil),  // 4: commu_module.SetupCommitteeRequest
	(*SetupCommitteeResponse)(nil), // 5: commu_module.SetupCommitteeResponse
	(*LeaveRequestResponse)(nil),   // 6: commu_module.LeaveRequestResponse
	(*RequestLeaderRequest)(nil),   // 7: commu_module.RequestLeaderRequest
	(*RequestLeaderResponse)(nil),  // 8: commu_module.RequestLeaderResponse
}
var file_blockchain_interface_proto_depIdxs = []int32{
	3, // 0: commu_module.SetupCommitteeRequest.vrfResult:type_name -> commu_module.vrfValue
	1, // 1: commu_module.BlockchainInterface.EnrollNodeInfo:input_type -> commu_module.NodeData
	4, // 2: commu_module.BlockchainInterface.SetupCommittee:input_type -> commu_module.SetupCommitteeRequest
	1, // 3: commu_module.BlockchainInterface.LeaveRequest:input_type -> commu_module.NodeData
	7, // 4: commu_module.NetworkInterface.RequestLeader:input_type -> commu_module.RequestLeaderRequest
	2, // 5: commu_module.BlockchainInterface.EnrollNodeInfo:output_type -> commu_module.EnrollAccountResponse
	5, // 6: commu_module.BlockchainInterface.SetupCommittee:output_type -> commu_module.SetupCommitteeResponse
	0, // 7: commu_module.BlockchainInterface.LeaveRequest:output_type -> commu_module.Empty
	8, // 8: commu_module.NetworkInterface.RequestLeader:output_type -> commu_module.RequestLeaderResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blockchain_interface_proto_init() }
func file_blockchain_interface_proto_init() {
	if File_blockchain_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchain_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnrollAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupCommitteeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetupCommitteeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveRequestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestLeaderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestLeaderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_blockchain_interface_proto_goTypes,
		DependencyIndexes: file_blockchain_interface_proto_depIdxs,
		MessageInfos:      file_blockchain_interface_proto_msgTypes,
	}.Build()
	File_blockchain_interface_proto = out.File
	file_blockchain_interface_proto_rawDesc = nil
	file_blockchain_interface_proto_goTypes = nil
	file_blockchain_interface_proto_depIdxs = nil
}
